services:
  - type: web
    name: streamsmart-backend
    env: python
    buildCommand: "pip install -r requirements_render.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: LIGHTWEIGHT_BERT_ENABLED
        value: "true"
      - key: AUTO_FETCH_FREE_PROXIES
        value: "true"
    healthCheckPath: /health 