services:
  - type: web
    name: streamsmart-backend
    env: python
    buildCommand: pip install -r requirements_light.txt
    startCommand: python start.py
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true 